---
- name: Instalacion de productos en Windows 10
  hosts: all
  gather_facts: no
  vars:
    iis_test_message: Hola
    ambiente: Desarrollo
  tasks:

  - name: Crear la carpeta de configuracion
    win_file:
      path: C:\Temp\
      state: directory

  - name: Copiar los archivos de configuracion
    win_copy:
      content: "{{ iis_test_message }}"
      dest: C:\Temp\index.html

  - name: Crear un archivo desde plantilla jinja
    win_template:
      src: file.conf.j2
      dest: C:\Temp\file.conf


  - name: Mostrar la direccion del servidor
    debug:
      msg: "http://{{ ansible_host }}"

  - name: Download the Apache installer
    win_get_url:
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi

#  - name: Install MSI
#    win_package:
#      path: C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi
#      state: present

  - name: UnInstall MSI
    win_package:
      path: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi
      state: absent
